### ISSUE TITLE
Unnecessary zip file

### ISSUE THREAD

**Issue by rlorenzo** [colinperepelken/moodle-ltisource_message_handler#3]
In the deployment instructions it says:

- Download this repository.
- Extract the ZIP to 'mod/lti/source/'.
- The folder name within the source directory should be "message_handler".
- Login to your Moodle site as an administrator and install the plugin.

But the zip file in the repo appears to be the contents of the repo itself. Isn't it clearer to just rename the downloaded repo to message_handler and copy the folder to the mod/lti/source folder?

On our system we add plugins to our codebase using git submodules, so we would just create a submodule under mod/lti/source pointing to the master of this repo.

The extra, unnecessary zip file just adds bulk to the package.

**Comment by colinperepelken** [comment]
Hi @rlorenzo,

Thank you for creating this issue! I removed the zip file from the repository and added a new version (2.8) to the Moodle Plugins Directory. I believe the deployment instructions still make sense, so I left those unchanged. Let me know if you have any other suggestions or concerns! If not, I'll go ahead and close this issue.

Colin

**Comment by rlorenzo** [comment]
@colinbernard Yeah, there is a download as Zip option from Github, hopefully people know that already.

Thanks!
